name: Lint

on:
  pull_request:
    branches:
      - master

jobs:
  linux:
    name: Linux - Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
      - run: npm ci
      - run: |
          npm run commitlint -- \
          --verbose \
          --from `git merge-base origin/master $GITHUB_SHA`
      - run: npm run lint
